#!/bin/bash

sudo=""
usage="
rexec: a remote script executor
executes commands over ssh, using the options supplied.

rexec [-rh] [-h hosts] [-s script] [-c certificate] [hosts] [positional parameters]

Options:
	-r		execute commands using sudo
	-h		shows usage (this) and exits
	-H		list of hosts to connect to
	-s		the script to execute
	-c		a certificate to use for authentication
	-u		the user to log in as, defaults to ec2-user
All options can be supplied as a file or as a string"

while getopts ":rhc:H:u:s:" OPTOPT
do
  case $OPTOPT in
	r)
	  sudo="sudo"
	  ;;
	h)
	  echo "$usage"
	  exit 0
	  ;;
	c)
	  if [ -r "$OPTARG" ]
	  then
		cert="-i $OPTARG"	
	  else 
		cert="-i <($OPTARG)"
	  fi
	  ;;
	H)
	  if [ -r "$OPTARG" ]
	  then
		ips="$(cat $OPTARG)"	
	  else 
		ips="$OPTARG"
	  fi
	  ;;
	s)
	  if [ -r "$OPTARG" ]
	  then
		script="$(cat $OPTARG)"	
	  else 
		script="$OPTARG"
	  fi
	  ;;
	u)
	  user="$OPTARG"
	  ;;
	\?)
	  echo "invalid option: -$OPTARG" >&2
	  echo "$usage"
	  exit 1
  esac
done
shift $((OPTIND-1))

if [ -z "$ips" ]
then
  if (( $# > 0 ))
  then	
	ips="$1"
  else
	echo "must supply atleast one hostname" >&2
	echo "$usage"
	exit 1
  fi
  shift 1
fi


while read line
do
  echo $line
  command=$(base64 <( echo "$script") )
  ssh -n -tt $cert "${user:-ec2-user}"@"$line" "echo $command | base64 -d | $sudo bash -- /dev/stdin $@"
done <<< "$ips"
